spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/five_go
    username: root
    password:
  graphdb:
    url:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
